### ISSUE TITLE
ValueError("Not currently logged in.")

### ISSUE THREAD

**Issue by apfelsprudel** [bitchute-kodi/plugin.video.bitchute#8]
First, I like to thank you for your effort to bring this plugin to the world.
I have one problem and frankly, I am not getting it why, so I decided to open this issue.

My device I run Kodi with is a Amazon FireTV 4k Stick.
I have entered my user credentials in the plugin settings menu.
Every time I try to log in, I am getting this error:

> 2019-07-17 20:52:36.733 T:22866   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Not currently logged in.
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bitchute/main.py", line 686, in <module>
                                                router(sys.argv[2][1:])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bitchute/main.py", line 666, in router
                                                listSubscriptionVideos(int(params.get('page', '1')))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bitchute/main.py", line 505, in listSubscriptionVideos
                                                subs = fetchLoggedIn(baseUrl + "/subscriptions")
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bitchute/main.py", line 278, in fetchLoggedIn
                                                raise ValueError("Not currently logged in.")
                                            ValueError: Not currently logged in.
                                            -->End of Python script error report<--
2019-07-17 20:52:36.856 T:22865   ERROR: GetDirectory - Error getting plugin://plugin.video.bitchute/?action=subscriptionActivity
2019-07-17 20:52:36.859 T:6096   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bitchute/?action=subscriptionActivity) failed

I tryed to analyze this by myself and I figured out, that this happens because I don't get any cookies back from line 237 in main.py. Nothing gets written in the authCookies Array.

My settings.xml File looks like this:

> <settings version="2">
    <setting id="cookies">[]</setting>
    <setting id="password">My Password</setting>
    <setting id="save_path" default="true"></setting>
    <setting id="seed_after" default="true">false</setting>
    <setting id="username">my_user_name</setting>
</settings>

As I have seen @salfter has the same Issue in
https://github.com/bitchute-kodi/plugin.video.bitchute/issues/6

**Comment by jasonfrancis** [comment]
@apfelsprudel I recreated the problem you're describing by using
```xml
<setting id="cookies" value="[]" />
```
I resolved the problem with commit 433cd82, could you pull the latest version and see if it starts working for you?

**Comment by apfelsprudel** [comment]
You safed my day, this is working and resolved this Problem! Thank you very much!
